FROM python:3.5

#RUN mkdir /web
#WORKDIR /web

#ADD requirements.txt /web/requirements.txt
#ADD py_pkg /web/py_pkg

#RUN pip install --download="/web/py_pkg" -r requirements.txt
#RUN pip install --no-index --find-links="/web/py_pkg" -r /web/requirements.txt

#RUN pip download --no-index --find-links=/tmp/wheelhouse -d /tmp/otherwheelhouse SomePackage
#RUN pip download -d /web/py_pkg SomePackage
